### ISSUE TITLE
Styling a component

### ISSUE THREAD

**Issue by Stephen-Tsen** [styled-components/vue-styled-components#100]
I'm trying to style the [vue slide up down component ](https://www.npmjs.com/package/vue-slide-up-down) and am having issues doing so. My code is as follows.

```
const VueSlideUpDown = Vue.component('slide-up-down');
export const StyledSlideUpDown = styled(VueSlideUpDown)`
  ....
`;
```

I'm getting this error when trying to do so.
```vue-styled-components.es.js?9c56:3070 Uncaught Error: function VueComponent (options) {
      this._init(options);
    } is not allowed for styled tag type.
    at styled (vue-styled-components.es.js?9c56:3070)
    at eval (styled.js?b5e2:32)
    at Module../src/components/SlideUpOverlay/styled.js (app.js:7430)
    at __webpack_require__ (app.js:724)
    at fn (app.js:101)
    at eval (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/SlideUpOverlay/SlideUpOverlay.vue?vue&type=script&lang=js&:2)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/SlideUpOverlay/SlideUpOverlay.vue?vue&type=script&lang=js& (app.js:1489)
    at __webpack_require__ (app.js:724)
    at fn (app.js:101)
    at eval (SlideUpOverlay.vue?c6f3:1)```

Any help would be greatly appreciated.

**Comment by liqueflies** [comment]
Please provide a sandbox with your example :)

**Comment by Stephen-Tsen** [comment]
https://codesandbox.io/s/vue-template-99gbj

Let me know if there's anything else you need.

**Comment by joeharrison-code** [comment]
I am having a similar issue when trying to style router-link component: 

`import styled from 'vue-styled-components';

// unfortunately you can't import directly router-link, you have to retrieve contstructor
const RouterLink = Vue.component('router-link')

const StyledLink = styled(RouterLink)`
  color: palevioletred;
  font-size: 1em;
  text-decoration: none;
`;

export default StyledLink;
<styled-link to="/">Custom Router Link</styled-link>`

> Uncaught Error: undefined is not allowed for styled tag type.

Any help would be appreciated. OP have you got anywhere with this?

**Comment by joeharrison-code** [comment]
All I am doing is this .....

`
import Vue from "vue";
const RouterLink = Vue.component('router-link');
`

**Comment by Stephen-Tsen** [comment]
I haven't. I really wish I had the time to figure this out.

> I am having a similar issue when trying to style router-link component:
> 
> `import styled from 'vue-styled-components';
> 
> // unfortunately you can't import directly router-link, you have to retrieve contstructor
> const RouterLink = Vue.component('router-link')
> 
> const StyledLink = styled(RouterLink)`color: palevioletred; font-size: 1em; text-decoration: none;`;
> 
> export default StyledLink;
> Custom Router Link`
> 
> > Uncaught Error: undefined is not allowed for styled tag type.
> 
> Any help would be appreciated. OP have you got anywhere with this?

**Comment by liqueflies** [comment]
@joeharrison-code if you import 

```
import SlideUpDown from "vue-slide-up-down";
```

and instead of registering globally you just

```
styled(SlideUpDown)
```

Works for me.

**Comment by joeharrison-code** [comment]
Sorry, but that is Stephen-Tsen issue.

My issue is that styling router-link from documentation is not working.

Am I best to post this as a new issue?

Thanks for this beautiful library :)

**Comment by Stephen-Tsen** [comment]
I wasn't able to style router-link as well.

**Comment by letuankiet212** [comment]
I wasn't able to style router-link as well.
