### ISSUE TITLE
[BUG] Impossible to use themes

### ISSUE THREAD

**Issue by LKay** [styled-components/vue-styled-components#108]
The exported parts of library do no't conform the example and documentation. It is possible to define theme using `ThemeProvider` but `default` property/method on default export is not defined. It is not possible to call this:

```js
import styled from 'vue-styled-components';

const Foo = styled.default('div', {})`
  background: 'red';
`

const Bar = styled.default`
  background: 'blue';
`
```

**Comment by liqueflies** [comment]
Sorry, why are you using `default` if you are importing styled directly?

`styled.default` should be called on require, dynamic import, library referenced via inline script.
