### ISSUE TITLE
[FEATURE] Referencing other components

### ISSUE THREAD

**Issue by LKay** [styled-components/vue-styled-components#109]
This library seems to be compatible with original `styled-components` but with Vue flavor, however interpolation other components as defined in docs: https://styled-components.com/docs/advanced#referring-to-other-components doesn't work and throws compilation errors.

**Comment by AasmundEndresen** [comment]
I've also been getting errors when extending components as a styled components - as can be done with original styled-components.

Like when doing something in the flavor of:

```
const Container = styled.div`
  width: 100%;
  border: 1px solid black;
`;

const StyledPageContainer = styled(Container)`
  border-color: red;
`;

const StyledSubContainer = styled(Container)`
  border-color: green;
`;
```

This doesn't work as expected, could it be a related issue?

**Comment by liqueflies** [comment]
Referencing other components is not a bug, it's a new feature that SC original library made after the first implementation of this library.

@AasmundEndresen if you run the examples of this library this cases you are assuming not working it seems working
