### ISSUE TITLE
props does not work in keyframes

### ISSUE THREAD

**Issue by jessekalil** [styled-components/vue-styled-components#118]
I need to use props inside the keyframes, but it is not working!

```javascript
const spinner = primary => keyframes`
	0% {
		box-shadow: 0 0 0 .4em ${primary}, 0 0 0 .1em ${primary};
		transform:rotate(360deg);
	 }
        100% { box-shadow: 0 0 0 .4em ${primary}, 0 0 0 3.6em transparent; }
`
```

**Comment by liqueflies** [comment]
I think also in the main lib this feature is not present.

https://styled-components.com/docs/api#keyframes

**Comment by blaytenshi** [comment]
Actually what @jessekalil wrote does work in react version of styled components.

Example here: https://codesandbox.io/s/react-playground-rf12b?file=/src/StyledCompAnimationsExample/index.js

It's broken in the vue version of styled components.
