### ISSUE TITLE
How to add classes in vue3-styled-components

### ISSUE THREAD

**Issue by mockingjet** [styled-components/vue-styled-components#119]
I am using tailwindcss framework,  and I thought styled-components help me extract classes from these long class names.

From this official [FAQ](https://styled-components.com/docs/faqs#can-i-use-css-frameworks), I can use the "attrs" function to add classes.

But vue3-styled-components doesn't provide this function, then how to make it work?

    import styled from "vue3-styled-components";

    const backgroundImage = `url(${require('@/assets/entry-scene.png')})`;

    export const EntryBackground = styled('div', {})
      .attrs({
        class: 'w-screen h-screen flex justif-center items-center relative bg-top bg-contain bg-no-repeat',
      })`
        backgroundImage: ${backgroundImage}
      `;

It throws "TypeError: Object(...)(...).attrs is not a function"

**Comment by liqueflies** [comment]
Please take care that vue3-styled-components is not this repo.

https://github.com/UX-and-I/vue3-styled-components
