### ISSUE TITLE
selector with vue-styled-components

### ISSUE THREAD

**Issue by didemkome** [styled-components/vue-styled-components#121]
I can not reach an styled component under a wrapper.  I want to use a selector inside it but when i check it from chrome dev tools, styles doesn't seem correct.

```
export const ButtonWrapper = styled.div`
	display: flex;

	${PrimaryButton} {
		background: red;
	}
`;

```

**Comment by onurykaya** [comment]
i have a same problem

**Comment by tuceo** [comment]
Same here

**Comment by liqueflies** [comment]
Duplicated Issue, please see #97.
