### ISSUE TITLE
Uncaught TypeError: createElement is not a function

### ISSUE THREAD

**Issue by clark-john** [styled-components/vue-styled-components#141]
I was trying to register my component and use it, but this error occurred in __vue-styled-components.es.js:2969__. What do y'all think is the cause of this error? Or it is just a bug?

**Comment by vavellar** [comment]
same here

**Comment by vavellar** [comment]
https://github.com/UX-and-I/vue3-styled-components

**Comment by clark-john** [comment]
thanks for your response.
