### ISSUE TITLE
Adapting based on passing props - styled.default error

### ISSUE THREAD

**Issue by Jones-S** [styled-components/vue-styled-components#15]
Hi there

I tried to use your example to pass props and style a component depending on the value of the prop.
As you describe here https://github.com/styled-components/vue-styled-components#adapting-based-on-props I tried style a h1-tag.

But as soon as I changed this line I had:

```
const H1 = styled.h1`
```
To the expected
```
const H1 = styled.default('h1', titleProps)`
```

I received the following error:
`__WEBPACK_IMPORTED_MODULE_1_vue_styled_components__.a.default is not a function`

I checked your code and with trial and error I came up with 
```
const H1 = styled('h1', titleProps)`
```

I don't know whether this makes a difference. But it works like this. What would the style.default do? Or is it just a mistake in the docs?

**Comment by liqueflies** [comment]
Hi, it seems a mistake on the docs. I'll update soon!

Thank you!
