### ISSUE TITLE
Tag agnostic components

### ISSUE THREAD

**Issue by Jones-S** [styled-components/vue-styled-components#17]
Hi

Sorry for all my questions, but I'd like to build something like this:
https://github.com/styled-components/styled-components/issues/494

In my case a Title component where I can pass the h-level as a property.
I came up with this:

```
// components/Title/style.js

const properties = {
  tag: {
    type: String,
    default: 'h1'
  }
}

const Title = styled(properties.tag, properties)`
  color: red;
`
export default Title

```

and I use this like this: 
```
// components/Title/index.js

import Title from './style'

export default {
  name: 'Title',
  props: ['tag'],
  computed: {
  },

  render (h) {
    const { tag } = this

    return (
      <div>
        <Title tag={tag}>
          {this.$slots.default}
        </Title>
      </div>
    )
  }
}

```

Or for testing purposes on can also replace the `tag={tag}` with `tag='h3'`
This does not work though. properties.tag would not call the right value.

If I override properties at the beginning like this:
```
// components/Title/style.js

const properties = {
  tag: {
    type: String,
    default: 'h1'
  }
}

properties.tag = 'h2'

const Title = styled(properties.tag, properties)`
  color: red;
`
export default Title

```

It will indeed render an h2. But somehow I can't pass the props correctly.
And I would also really like to have the default value.

I did also have a look at the vue props validation, but I did not find a solution there:
https://vuejs.org/v2/guide/components.html#Prop-Validation

That's also where I got the idea with the default value for my prop.

Maybe someone has an idea how to build this?

**Comment by liqueflies** [comment]
You can use new method `withComponent`

[Check here](https://github.com/styled-components/vue-styled-components#withcomponent)

Thank you.
