### ISSUE TITLE
Adapting based on props doesn't work correctly (sometimes)

### ISSUE THREAD

**Issue by iamfrntdv** [styled-components/vue-styled-components#18]
Component that has css properties based on props conditionals sometimes may run into false statement so component will get unwanted css property value.

I was able to reproduce this bug by refreshing browser multiple times.
Tested both in latest chrome and safari.

**Comment by Jones-S** [comment]
Have not experienced this so far. Could you provide some code?

**Comment by liqueflies** [comment]
@iamfrntdv Can you reproduce the issue on a jsfiddle?

**Comment by iamfrntdv** [comment]
Code example - https://gist.github.com/iamfrntdv/1e6331d47c3bfb409e7f7bb3049ca786
all actions get data over some REST API.
Current fix for this bug was adding ```v-if``` like this:
```
featuredContent(v-if="editorsChoice !== '' ")
```

**Comment by liqueflies** [comment]
Is this related with #23 ?

**Comment by iamfrntdv** [comment]
It seems like #23 fixed this issue too.

**Comment by liqueflies** [comment]
Great :)
