### ISSUE TITLE
@supports CSS not supported

### ISSUE THREAD

**Issue by Jones-S** [styled-components/vue-styled-components#20]
As far as I can see the @supports rule https://developer.mozilla.org/en-US/docs/Web/CSS/@supports is not supported in vue styled components.

If anyone knows a hack, I would be glad to get to know.

Cheers

**Comment by liqueflies** [comment]
For me it's not dependency of vue-styled-components.

Use something like Modernizr?

**Comment by Jones-S** [comment]
In styled components they support it. And I would expect this to work:
```const H1 = styled.h1`
      color: green

    @supports (display: block) {
        & {
          color: red;
        }
    }
`
```
But the ampersand is not translated to the parent object...

in styled components they went a step further:
https://stackoverflow.com/questions/43562789/using-supports-with-styled-components
and even made it available without the ampersand, which would not be necessary in my opinion.
But anyway. I'll have a look at Modernizr. 👍

**Comment by liqueflies** [comment]
I'll take a look to handle `&` selector.

Thank you :)

**Comment by Jones-S** [comment]
Well thank you Sir :)

**Comment by Jones-S** [comment]
![image](https://user-images.githubusercontent.com/7059580/27602193-347ee434-5b72-11e7-9be4-c47ff72817ca.png)


![image](https://user-images.githubusercontent.com/7059580/27602214-477a01e0-5b72-11e7-93b8-80f7abac8cde.png)

Somehow it does work. At one place It inserts the right code, but at some other place it seems to insert the ampersand.

```
   // part of the fontStyleOutlineHeading function
...
    @supports (text-stroke: 1px black) {
     & {
       text-stroke: 1px #46df96;
       text-shadow: none;
     }
   }
...
```

It even seems to insert vendor prefixes.
At the same time it seems to break...
I have a rule:

```
  > a {
    ${fontStyleOutlineHeading({ color: variables.sColorBlack })}
    // BREAKS here
    display: block;
  }
```

and the display block rule is not applied anymore... I'll try to investigate a bit more :v:

**Comment by Jones-S** [comment]
Well I don't understand: It seems that it does not break it completely but as if it travels up one level. so everything after the @supports rule is applied to the parent again:

```
const Menu = styled('div', styleProps)`
  …

  > a {
    ${fontStyleOutlineHeading({ color: variables.sColorBlack })} // contains the @supports rule
    background-color: rgb(230, 221, 108);
    display: block;
  }
`

```

Where I have this fontStyleOutlineHeading function:
```
export function fontStyleOutlineHeading ({ color: color } = { color: variables.sColorGreen }) {
  return css`
    color: #fff;
    text-shadow: -1px -1px 0 ${color},
    1px -1px 0 ${color},
    -1px 1px 0 ${color},
    1px 1px 0 ${color};

    @supports (text-stroke: 1px black) {
     & {
       text-stroke: 1px ${variables.sColorGreen};
       text-shadow: none;
     }
   }
  `
}
```

The background-color which is clearly applied to the a tag is now applied to the parent of the a:
![image](https://user-images.githubusercontent.com/7059580/27611490-a27f6c04-5b92-11e7-9922-1f6ef4fabb5a.png)

And the resulting css:
```
.ShjaQ>a {
  -webkit-text-stroke: 1px #46df96;
  text-stroke: 1px #46df96;
  -webkit-text-shadow: none;
  text-shadow: none;
}

.ShjaQ {
  background-color: rgb(230, 221, 108);
  display: block;
  font-weight: 600;
  margin: 1.25rem;
}
```

I believe that somehow one pair of curly brackets is set incorrectly.

I also tried to make a second rule after the breaking line:
```
const Menu = styled('div', styleProps)`
 …

  > a {
    ${fontStyleOutlineHeading({ color: variables.sColorBlack })} // breaks here
  }

  > a { // add a second ruleset for the same selector
    background-color: rgb(230, 221, 108);
    display: block;
  }
`
```

Which results in this css:
```
.cbEYgM>a {
  -webkit-text-stroke: 1px #46df96;
  text-stroke: 1px #46df96;
  -webkit-text-shadow: none;
  text-shadow: none;
}


} // Where is this bracket coming from???
.cbEYgM>a {
  background-color: rgb(230, 221, 108);
  display: block;
  font-weight: 600;
  margin: 1.25rem;
}
```

Unfortunately this results in invalid css – or at least the second block is applied nowhere.

A workaround for the wanted behaviour would include omitting one bracket like this:
```
> a {
    ${fontStyleOutlineHeading({ color: variables.sColorBlack })}
// no closing bracket here

  > a {
    background-color: rgb(230, 221, 108);
    display: block;
```

![image](https://user-images.githubusercontent.com/7059580/27611832-104e3c3c-5b94-11e7-89b5-ffccc993ad43.png)


I would love to fix it by myself, but I don't feel capable of understanding how vue styled components works, so unfortunately that's all I can do for now. I hope this helps finding the problems...
Cheers

**Comment by Jones-S** [comment]
Could you check on the & handler so far?

**Comment by liqueflies** [comment]
I've pushed a new version **1.4.12**

In the examples section there is a `@supports` example, and it's working.

Thank you for reporting :)
