### ISSUE TITLE
Show class name for debugging of vue styled components

### ISSUE THREAD

**Issue by Jones-S** [styled-components/vue-styled-components#21]
It's me again.
Just wondering if you have a simple solution for this:
For debugging purposes I'd like to have the component name displayed as a class (or any other helper to show which component is rendered). I found this:
[Babel plugin for styled components ](https://github.com/styled-components/babel-plugin-styled-components) BUT https://github.com/styled-components/babel-plugin-styled-components/issues/60 it does not work with vue styled components. If anyone comes up with a solution, let me know 😄

**Comment by liqueflies** [comment]
Hi @Jones-S,
I think this is not the work that vue-styled-components should do.

Using Vue DevTools you can have the name of component and the generatedClassName :)
