### ISSUE TITLE
How to style Router Link

### ISSUE THREAD

**Issue by iamfrntdv** [styled-components/vue-styled-components#27]
Is there any example how to style router-link?

**Comment by liqueflies** [comment]
Hi @iamfrntdv,
I'm Working on it.

For now there isn't a way, probably workaround can be style with `> a` selector from a parent styled-component for now.

I'll be working on it soon

**Comment by liqueflies** [comment]
Hi @iamfrntdv,
with new update you can also style `router-link`!

Check the section on readme:
https://github.com/styled-components/vue-styled-components#style-router-link

**Comment by letuankiet212** [comment]
Hi , i have error when use router link , anyone can help me :( 
![image](https://user-images.githubusercontent.com/48205415/116020944-72a71580-a671-11eb-90ff-9bb16689ff12.png)
