### ISSUE TITLE
How to use `ref`?

### ISSUE THREAD

**Issue by JasinYip** [styled-components/vue-styled-components#31]
I have no idea how to use [ref](https://vuejs.org/v2/api/#ref) with vue-styled-components. I've tried like this:

```vue
<template>
  <FooBar ref="foobar"></Foobar>
</template>

<script>
import styled from 'vue-styled-components'
export default {
  mounted () {
    console.log(this.$refs.FooBar)  // => VueComponent
  },
  components: {
    FooBar: styled.div`
      height: 100px;
      width: 100px;
    `
  }
}
</script>
```

It would log a VueComponent.

I've found this issue https://github.com/styled-components/styled-components/issues/102 in styled-components repository, and I've tried to change `ref` to `innerRef`, it didn't work either.

So, how should I fix this problem? Thanks a lot!

**Comment by liqueflies** [comment]
Hi @JasinYip, are you trying to get the DOM element or the component instance?

According to the docs https://vuejs.org/v2/api/#ref
`If used on a plain DOM element, the reference will be that element; if used on a child component, the reference will be component instance`

If you want to get the DOM element you have to use `this.$refs.FooBar.$el`.

Let me know if it works also for you.

**Comment by JasinYip** [comment]
It works! Thanks @liqueflies !
