### ISSUE TITLE
router-link not mounted in vue-loader

### ISSUE THREAD

**Issue by ShiningDan** [styled-components/vue-styled-components#32]
I init the vue project with vue-cli wepack mode like this:
```
vue init webpack vue-test
```
and use vue-styled-components to wrap router-link,

```vue
<template>
  <div id="app">
    <StyledLink1 to="/">link 1</StyledLink1>
    <StyledLink2 to="/foo">link 2</StyledLink2>
    <router-view/>
  </div>
</template>

<script>
import Vue from 'vue'
import styled from 'vue-styled-components'

const RouterLink = Vue.component('router-link')

const StyledLink1 = styled(RouterLink)`
  color: red
`

const StyledLink2 = styled(RouterLink)`
  color: green
`

export default {
  components: {
    StyledLink1,
    StyledLink2
  }
}
</script>
```
but after run `npm run dev`, the router-link do not mount in dom tree:

<img width="437" alt="demo" src="https://user-images.githubusercontent.com/23012618/33115567-6cc5f35c-cf9c-11e7-878c-3d0f45ef0ea3.png">

What confused me is that after modify some code and trigger HMR, the router-link automatically appears:

<img width="519" alt="demo2" src="https://user-images.githubusercontent.com/23012618/33115900-afc0c276-cf9d-11e7-8c14-349abf663d49.png">

Can you help solve this problem? Thanks a lot!

**Comment by liqueflies** [comment]
Hi @ShiningDan,
The problem is that on vue-cli you have `router-link` after `Vue.use(VueRouter)`.

Probabily you import (and you do right) your app component before `Vue.use(VueRouter)`.

I have to find a way to integrate inside the lifecycle of the component, this will fix the problem.

I let you know soon. Thanks for reporting :)

**Comment by izakfilmalter** [comment]
@liqueflies Is there a simple solution that we can do to solve this bug? Currently have it in a project.

**Comment by liqueflies** [comment]
Hi @izakfilmalter, @ShiningDan.

This is related in how Vue works.

If you import your app.vue before `Vue.use(VueRouter)` it will not work.

Please move the whole router setup into separate file then import _before_ the app.vue import.

**Comment by rogierverbrugge** [comment]
I tried the above but could not get it to work. What did work was:

```ts
// StyledLink.ts

import Vue from 'vue'
import styled from 'vue-styled-components';
import Router from 'vue-router'

Vue.use(Router)

const RouterLink = Vue.component('RouterLink')

const Link = styled(RouterLink)

export default Link
```

@liqueflies is this solution any good?

**Comment by zuxriddinkamalov** [comment]
@liqueflies your solution is not helped. That is the example that you wrote in the documentation. 

> "vue": "^2.6.10",
> "vue-router": "^3.1.3",

`
import Vue from 'vue'
import styled from 'vue-styled-components';
import Router from 'vue-router'

Vue.use(Router)

const RouterLink = Vue.component('RouterLink')

const Link = styled(RouterLink)

export default Link
`
This code to. The value of RouterLink is undefined. Maybe there is some other solution?
