### ISSUE TITLE
Change which tag or component a styled component renders

### ISSUE THREAD

**Issue by adamsoffer** [styled-components/vue-styled-components#33]
The React implementation has an [escape hatch](https://www.styled-components.com/docs/basics#extending-styles) which allows you to extend the styles of another component and use a different tag.

What is the best way to achieve this in the vue implementation?

**Comment by liqueflies** [comment]
You can still use `styled(MyStyledComponent)`

isn't true?

**Comment by bennpearson** [comment]
Missing the `as` polymorphic prop: https://www.styled-components.com/docs/api#as-polymorphic-prop

**Comment by liqueflies** [comment]
You can use the `withComponent` method now.

[Check here](https://github.com/styled-components/vue-styled-components#withcomponent)

Thank you.
