### ISSUE TITLE
Event handlers are not applied

### ISSUE THREAD

**Issue by Munter** [styled-components/vue-styled-components#35]
Event handlers on styled components are not working. It seems the created component is not applying the right vue properties that contain things like event handling.

Recreation:

```jsx
const Button = styled.button``;

const Component = Vue.component("test-component", {
	functional: true,

	render() {
		return <Button onClick={() => console.log("I am never fired")}>Click me!</Button>;
	}
});
```

Expected behavior: Clicking the button should log `I am never fired` in the console

Actual behavior: Nothing gets logged in the console

**Comment by liqueflies** [comment]
Hi @Munter,
I assume this is the same problem as `router-link` and any vue-components.

You must apply the native modifier, but I don't know how to do in jsx.

Can you try this?

**Comment by Munter** [comment]
Yeah, we got it to work with `<Button nativeOnClick={() => console.log("I am never fired")}>Click me!</Button>`. I can move forward without being blocked, but I guess it would be nice to get the higher level event handlers integrated into vue-styled-components in order to retain the semantics that the rest of the ecosystem provides

**Comment by liqueflies** [comment]
I can easily achieve this issue. Just give me some time to update, also PR's are well accepted.

**Comment by Munter** [comment]
I'm trying to clear some time at work to contribute here, but it's not my core responsibility, so it might be a bit difficult unless we hit a hard blocker

**Comment by kurikaesu** [comment]
Any updates on this issue?

**Comment by liqueflies** [comment]
@Munter @kurikaesu I am trying to achieve this but it's quiete difficult because to bridge the vue event you have to emit from the base component:

https://jsfiddle.net/Linusborg/q4j5xm98/

We can't know which component will be rendered. any ideas?

**Comment by liqueflies** [comment]
I bridged click so for now you will be able to use "click" handler.

I don't know which events are you also interested.
