### ISSUE TITLE
v-model not working 

### ISSUE THREAD

**Issue by Bensigo** [styled-components/vue-styled-components#36]
when i try using v-model on a styled-component is not working
```
<Select v-model="TransactionDetail.country">
      <option v-for="country in countries" :key="country.id">{{country.name}}</option>
 </Select>
```

**Comment by liqueflies** [comment]
Thanks for reporting, this was obviously a critical issue and solved in 1.2.2, just update your repo.

👋

**Comment by Bensigo** [comment]
Thanks

**Comment by robinwkurtz** [comment]
I'm running into this issue on `1.5.1`. My inputs are returning as empty.

Thanks for port!

**Comment by iwasaki-kenta** [comment]
Wanted to know if it was specifically fixed within v1.2.3; tried it out with this example just now:

```
<Column style="flex: 1;">
                <Row>
                    <Input type="text" v-model="privateKey" @input="validatePrivateKey"/>
                </Row>
                <Row>
                    <Input type="text" v-model="publicKey" disabled/>
                </Row>
            </Column>
```

```
const Input = styled.input`
        width: 100%;
    `
```

**Comment by liqueflies** [comment]
Sorry @iwasaki-kenta I didn't get the problem.

**Comment by iwasaki-kenta** [comment]
@liqueflies With the code above, styled text inputs w/ v-model `privateKey` and `publicKey` seem to have null/empty values (they don't seem to be passed in).

I tried it out on both v1.2.2 and v1.2.3; I'm not too sure but it could be because in your commit:

```
on: {
              input: (event) => {
                this.$emit('input', event.target.value)
              }
            }
```

it does not take into account the additional input listener I attached to text input w/ v-model `privateKey`.

**Comment by liqueflies** [comment]
@iwasaki-kenta I've done it exactly how docs said:

https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components

the `<Input>` component is not a native input right?
If yes, you have to bridge up native event in the same way, so in your Input component do something like:

`<input class="my-fancy-input" @input="$emit('input', $event)" />`

**Comment by danwinterwijntjes** [comment]
I have a fix for this problem. https://github.com/styled-components/vue-styled-components/pull/45.

**Comment by liqueflies** [comment]
Hello,
Thanks to @fsodano #88 do the job.

Thank you.
