### ISSUE TITLE
Add a list of unsupported features to the readme?

### ISSUE THREAD

**Issue by Aaron-Pool** [styled-components/vue-styled-components#39]
Hey there, I'm a big styled-components fan, but my team has decided to go with Vue instead of react. As someone who would be interested in contributing to help backport styled component features, it would be helpful if there was a comprehensive list of unsupported features in the readme (as well as a contribution guide, perhaps?).

Thanks!

**Comment by liqueflies** [comment]
Check the answer on number #34 
styled-components and vue-styled-components should match the same codebase (it's not now).

I can't update the core manually each time and this should be a monorepo with the core one.
After that, implements the other functionalities on vue it's easier to maintain.

**Comment by Aaron-Pool** [comment]
So, is there something I can do help that happen maybe? Make an issue on the styled components monorepo requesting this? Anything?

**Comment by liqueflies** [comment]
We need to find a bunch of people to do the work. we have to isolate the react core from SC core and then write on top vue core.

This is my idea, maybe start a discussion on the main repo is a good idea but is better to find some people. 

We can place a message on top of README. what do you think?

**Comment by mxstbr** [comment]
This is very relevant, please comment here: https://github.com/styled-components/styled-components/issues/588 We basically just need somebody to tackle that issue.

**Comment by liqueflies** [comment]
@mxstbr this issue is exactly what I thought!

:)

basically in this comment:

https://github.com/styled-components/styled-components/issues/588#issuecomment-346798572

Just add styled-components-vue.

I can help for this, but I need people with lerna and sc core knowledge.
