### ISSUE TITLE
Vue Styled with Pseudo

### ISSUE THREAD

**Issue by badman-rodriguez** [styled-components/vue-styled-components#41]
Not sure what im doing wrong... 

but this:
```
export const backgroundExample= styled.div`
background: black;
height: 50px;
width: 50px;

&:hover {
    background: yellow;
  }
`
doesn't work for me... 

Dependencies

```
    "vue": "^2.5.2",
    "vue-router": "^3.0.1",
    "vue-styled-components": "^1.2.3"
```

devDependencies
```
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
```

**Comment by liqueflies** [comment]
I've pushed a new version **1.4.12**

In the examples section there is a `&:hover` example, and it's working.

Thank you for reporting :)
