### ISSUE TITLE
styled.keyframes not working

### ISSUE THREAD

**Issue by Andrei997** [styled-components/vue-styled-components#50]
I recently wanted to create a custom animation for a VUE component.
When I try to create the animation with `styled.keyframes` ... I get an error in my Webpack build (Nuxt JS) 
`__WEBPACK_IMPORTED_MODULE_0_vue_styled_components___default.a.keyframes is not a function`
  Does anyone have any idea why this is happening, the normal styled.span and alike work just fine ...

**Comment by Andrei997** [comment]
My `styled.span` looks like this
`
animation: ${animation} 1s
`
and my animation `styled.keyframes` is
`
    0% {left: 0;}
    50% {left: 50%;}
    100% {left: 0;}
`

**Comment by liqueflies** [comment]
Hi @Andrei997 ,
this PR https://github.com/styled-components/vue-styled-components/pull/48 manage keyframes and we will soon published I can't work well now because I have no wifi.

Just wait and soon you'll updated :)

**Comment by Andrei997** [comment]
@liqueflies Yessir!
