### ISSUE TITLE
corejs error right after install

### ISSUE THREAD

**Issue by eyar** [styled-components/vue-styled-components#59]
**Version**
3.0.4

**Node and OS info**
Node v10.7.0 / Yarn 1.9.4 / Windows 10

**Steps to reproduce**
vue create hello-world
cd hello-world
yarn add vue-styled-components
yarn serve

**What is expected?**
Vue starts serving

**What is actually happening?**
The following error is thrown:

```
This dependency was not found:

* core-js/modules/es7.promise.finally in ./src/main.js

To install it, you can run: npm install --save core-js/modules/es7.promise.finally
```

**Comment by liqueflies** [comment]
It's just node version.

Please use v8.x.x for now with something like nvm at the moment.
