### ISSUE TITLE
Event Handlers not passed to Styled Component

### ISSUE THREAD

**Issue by Jmeyering** [styled-components/vue-styled-components#62]
I'm attempting to pass onChange and onKeyup events into my styled components but they are not registering appropriately.

```
export default {
  render(h, c) {
    return (<StyledComponent onChange={c.props.onChange} onKeyup={c.props.onKeyup} />);
  }
}
```

none of the listeners attach to the component.

**Comment by liqueflies** [comment]
Have you tried use native event as described #19?

https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components
