### ISSUE TITLE
Extend Nested components using props

### ISSUE THREAD

**Issue by kushalmahajan** [styled-components/vue-styled-components#63]
Even though, it's mentioned in docs to use `Row.extend` for it. It works infact.
But what if I've props to be used alongside. How can I do that with extended component ?

I tried doing it with my Item component like below

```
const VItem = Vue.component(InlineItem);
export const Item= styled(VItem , itemProps);
```

This won't even render content inside Item.

**Comment by kushalmahajan** [comment]
Even though, it's mentioned in docs to use `Row.extend` for it. It works infact and error is no more there. 
But what if I've props to be used alongside. How can I do that with extended component ?

**Comment by matthewattanasio** [comment]
I too have this issue, is there a solution?

**Comment by liqueflies** [comment]
Hello,

I think is because you are not calling the function if you are not using backthicks.
[Please read here to know more](https://www.styled-components.com/docs/advanced#tagged-template-literals)

I tried a similar demo, and it's working.
Please call the `styled` function like this:

```
export const Item= styled(VItem , itemProps)``;
```
