### ISSUE TITLE
ThemeProvider dynamic props not working

### ISSUE THREAD

**Issue by sudheerj** [styled-components/vue-styled-components#69]
Hello,
        When I tried to assign dynamic value for ThemeProvider component the updated prop value is not available in the child components. i.e, it is not re-rendering based on prop binding.

` <theme-provider :theme="{color: $store.getters['themeColor'] }">`

**Comment by liqueflies** [comment]
Can you provide a complete example on codesandbox?

Thankyou,

Lorenzo

**Comment by Gramatiik** [comment]
Hello @sudheerj,

I was trying to implement something similar with provide/inject when I finally decided to [read the docs](https://vuejs.org/v2/guide/components-edge-cases.html#Dependency-Injection) 😄 just to realise that injected values are not reactive 🙁 

It looks like the current implementation of the **ThemeProvider** doesn't allow to have dynamic themes...

**Comment by liqueflies** [comment]
Could you please share a sandbox with the non-working example?

**Comment by Gramatiik** [comment]
Yes sure, here is a [minimal working example](https://github.com/Gramatiik/vue-styled-components-theme-provider). 🙂

**Comment by Gramatiik** [comment]
@liqueflies Any updates on this? 🤓

**Comment by m-sebastiyan** [comment]
Created a PR
https://github.com/styled-components/vue-styled-components/pull/81

**Comment by m-sebastiyan** [comment]
A support for dynamic props was added in **1.4.6**

**Comment by liqueflies** [comment]
Merged in #81 thanks to @m-sebastiyan ! <3
