### ISSUE TITLE
Props in Components Section?

### ISSUE THREAD

**Issue by WoofMeowEtc** [styled-components/vue-styled-components#73]
Hey.  First of all: this is amazing.  Real evolutionary step forward for what is just a plainly better rendering engine than React.  Wanted to give you huge props for this awesome software and please keep it coming - this is one of the first major steps forward in frontend in terms of real practical workflow acceleration and clarity in years, and being able to use it in Vue is so valuable I can't even put it into words - awesome stuff.

Here's my issue: I want to pass props to a Vue component and use them to set up some styled components within it.  Sounds simple right?

```
<script>
	import styled from 'vue-styled-components';

	export default {
		name: 'formatted-box',
		props: ['width', 'height'],
		components: {
			FormattedBox: styled.div`
				background-color: red;
				with: ${this.$props.width}px;
				height: ${this.$props.height}px;
			`;
		}
	}
</script>

<template>
	<FormattedBox>Yay I'm the right size!</FormattedBox>
</template>
```

The problem is, I don't have access to "this" or "props" at that time.  Is there something I'm missing?

The declarative nature of this syntax combined with the ability to respond to props in layout formatting would be a huge win for my workflow and while I can't speak for anyone else I think it would also be great for a lot of other people.  Is this possible, and if so, how, and if not, is it something you would consider for the future?

Thanks!

**Comment by liqueflies** [comment]
This usage is wrong, you should use 

```
styled.div`
  background-color: red;
  with: ${props => props.width}px;
  height: ${props => props.height}px;
`;
```
