### ISSUE TITLE
Styling an already present & globally registered SFC component

### ISSUE THREAD

**Issue by pachiraDIG** [styled-components/vue-styled-components#82]
Let's say I'm working inside an SFC and have imported and inserted another globally registered SFC:
```
<template>
    <div class="container">
        <anotherSFC></anotherSFC>
    </div>
</template>
```
How can I style `anotherSFC`? 

I'm only seeing instructions for creating new components. Is it possible to style already-created globally-registered components?

**Comment by jumpleGo** [comment]
You can probably style this component only inside it in the style tag. Or in the parent company, but then errors may occur.

**Comment by liqueflies** [comment]
Hello,

I think you can do like that.
In your `.vue`:

```
<script>
const AnotherSFC = Vue.component('another-sfc') // use the right component name
const EnanchedAnotherSFC = styled(AnotherSFC)`
  /* your style */
`

export default {
  components: {
    EnanchedAnotherSFC
  }
}
</script>

<template>
    <div class="container">
        <enhanced-another-sfc></enhanced-another-sfc>
    </div>
</template>
```
