### ISSUE TITLE
🥔 Proposal: Filtering of style props registration method.

### ISSUE THREAD

**Issue by codebender828** [styled-components/vue-styled-components#89]
Thanks to the styled components team for the work done with this. I'm currently using it to build a components library and I've run into one common problem I'm seeing a lot. With this issue I'd like to also kindly propose that an API to solve this issue is provided.🙏🏽

### Prop filtering
Currently the `styled()` API is unable to filter and therefore not evaluate props that are not passed from the component. This means that for every component I create, instead of reusing a single base `Box` component, I need to manually register all the style props declared on the component.

Prop filtering will allow the component to only forward props that are declared on the component. 

**Example Problem**
I have a `Box` component with props: `color` and `background`.
```js
// I'm using styled system for style functions.
import { color,  background, compose } from 'styled-system'

// Composing style functions
const baseProps = compose(color, background)

// Instantiation of Box component
const Box = styled('div', {
  color:  [String, Array],
  backgroundColor: [String, Array]
})(baseProps)
```
Next I declare my component in `App.vue`
```vue
<!-- App.vue -->

<!-- Notice that the `background-color` prop is not provided -->
<Box color="blue">
  This is some random box text
</Box>
```
The resulting css for my Box component is as follows:
```css
/* Random generated hash */
.s44ndx {
  color: 'blue';
  background-color: undefined; /* <--- This prop should not be registered if it's not declared
  on the <Box/> component in App.vue  */
}
```
This prevents me from reusing this `<Box/>` component in other places without needlessly long props object.

### Proposed API
The proposed API is for a method/function that will dynamically register props only if they are declared on the component(if possible). A similar implementation of one such function is the [`@styled-system/should-forward-prop`](https://github.com/styled-system/styled-system/tree/master/packages/should-forward-prop) function, `{ createShouldForwardProp }` used in React.

**What will it do?** 
This function will iterate over all the props declared on the <Box /> component and only register style props that are declared. The desired result will be smaller CSS as shown below:
```css
/* Random generated hash */
.s44ndx {
  color: 'blue';
}
```
This will allow for better of reusability and composability of components like the `<Box/>` component.

**Possible solutions** 
- Make use of Vue's `$props` API.
- Make use of Vue's `attrs` API to register non HTML attibute `attrs` values as style props for the component.

**Comment by codebender828** [comment]
Closing this issue seeing as there is no need for one such API. I was able to implement a filter in the templete literal functions in the styled API method. Below is how one can filter props as desired to generate only declared styles:

```js
// Import style functions from styled system as well as `compose` utility.
import { layout, color, space, background, border, compose }  from 'styled-system'
import { baseBoxProps } from './props' /* Imports all prop types for this component */

// Compose @style-system style functions
const systemProps = compose(
  layout,
  color,
  space,
  background,
  border
)


/**
 * @description Clears out all undefined props that are undefined from the props object
 * @param {Object} props
 * @returns {Object} Sanitized props object with defined values.
 */
function cleanProps (props) {
  for (const prop in props) {
    if (/* props[prop] === null|| */ props[prop] === undefined) {
      delete props[prop]
    }
  }
  return props
}

/**
 * Note: All styled components in vue-styled-components forward all their props.
 * If the prop is not registered in the child, it is then it is bound as a native
 * HTML attribute
 * @see https://github.com/styled-components/vue-styled-components#passed-props
 */
const Box = styled('div', {
  ...baseBoxProps
})`
  ${props => {
    //  👇🏽 This function performs the prop filtering and then registers those styled dynamically.
    const sanitizedProps = cleanProps(props)
    return system(sanitizedProps)
  }}
`
```

**Comment by diegoarcega** [comment]
This doesn't work well with Typescript, the props from the styled() conflicts with props from styled-system.
