### ISSUE TITLE
Props not being passed through

### ISSUE THREAD

**Issue by AasmundEndresen** [styled-components/vue-styled-components#99]
It seems that props arent passed through to the styled component, but rather just passed on in $vm.$attrs to the DOM node.

```import styled, { css } from 'vue-styled-components';

const StyledButton = styled.button`
  ${(props) => css`
    ${console.log(props)}
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    padding: ${props.theme.btn.padding};
    font-weight: ${props.theme.btn.fontWeight};
    font-size: ${props.theme.btn.fontSize};
    font-family: ${props.theme.btn.fontFamily};
    text-transform: uppercase;
    border-radius: ${props.theme.btn.borderRadius};
    min-height: ${props.theme.btn.minHeight};
    &:focus {
      outline: none;
    }
    &:disabled {
      opacity: 0.5;
    }
  `}
`;

export default StyledButton;
// things with props.variant are not working yet:

// border: ${props.theme.btn[props.variant].borderStyle};
// background-color: ${props.theme.btn[props.variant].backgroundColor};
// background-color: ${props.theme.btn[props.variant].color};
// width: ${props.theme.btn[props.size]};
// &:active {
//   background-color: ${props.theme.btn[props.variant].activeColor};
// }
```

Used in this component:

```<template>
  <styled-button
    :variant="computedVariant"
    :size="size"
    @click="act"
  >
    <slot />
  </styled-button>
</template>
<script>```

**Comment by AasmundEndresen** [comment]
Yields the following results:

![image](https://user-images.githubusercontent.com/28097617/68925808-4270fd00-0784-11ea-99de-e94912aced3e.png)
![image](https://user-images.githubusercontent.com/28097617/68925818-4ac93800-0784-11ea-9735-b60ed782a27e.png)
![image](https://user-images.githubusercontent.com/28097617/68925953-967be180-0784-11ea-8801-6a13467f9456.png)

**Comment by liqueflies** [comment]
This is not correct. You have to declare your props before using them.

Please read here:
https://github.com/styled-components/vue-styled-components#adapting-based-on-props

Good Luck :)

**Comment by ashbuilds** [comment]
@liqueflies But props should be passed to vue components, after defining props of styled components its not passing to vue components. Its either vue props or styled-props which is not correct as per react styled components.
![Screenshot 2020-01-30 at 3 55 31 PM](https://user-images.githubusercontent.com/2686288/73434247-f4c66280-4378-11ea-971b-5976b5aa19c5.png)

![Screenshot 2020-01-30 at 3 56 03 PM](https://user-images.githubusercontent.com/2686288/73434288-060f6f00-4379-11ea-8dd3-1c60764b0ae3.png)

So `disabled` props will not pass to vue component if i defined this as styled component props.
